from datetime import datetime
import joblib

def days_between(d1, d2):
    d1 = datetime.strptime(d1, "%d-%m-%Y")
    d2 = datetime.strptime(d2, "%d-%m-%Y")
    return abs((d2 - d1).days)

model = joblib.load("trained_country_new_case_predictor.pkl")

days = days_between("31-12-2019", "31-03-2020")

to_be_prediected = [
    11422068, #'popData2018',
    days, # 'day',
    0, #'countriesAndTerritories_Albania',
    0, #'countriesAndTerritories_Algeria',
    0, #'countriesAndTerritories_Afghanistan',
    0, #'countriesAndTerritories_Andorra',
    0, #'countriesAndTerritories_Angola',
    0, #'countriesAndTerritories_Antigua_and_Barbuda',
    0, #'countriesAndTerritories_Argentina',
    0, #'countriesAndTerritories_Armenia',
    0, #'countriesAndTerritories_Aruba',
    0, #'countriesAndTerritories_Australia',
    0, #'countriesAndTerritories_Austria',
    0, #'countriesAndTerritories_Azerbaijan',
    0, #'countriesAndTerritories_Bahamas',
    0, #'countriesAndTerritories_Bahrain',
    0, #'countriesAndTerritories_Bangladesh',
    0, #'countriesAndTerritories_Barbados',
    0, #'countriesAndTerritories_Belarus',
    1, #'countriesAndTerritories_Belgium',
    0, #'countriesAndTerritories_Belize',
    0, #'countriesAndTerritories_Benin',
    0, #'countriesAndTerritories_Bermuda',
    0, #'countriesAndTerritories_Bhutan',
    0, #'countriesAndTerritories_Bolivia',
    0, #'countriesAndTerritories_Bosnia_and_Herzegovina',
    0, #'countriesAndTerritories_Brazil',
    0, #'countriesAndTerritories_British_Virgin_Islands',
    0, #'countriesAndTerritories_Brunei_Darussalam',
    0, #'countriesAndTerritories_Bulgaria',
    0, #'countriesAndTerritories_Burkina_Faso',
    0, #'countriesAndTerritories_Cambodia',
    0, #'countriesAndTerritories_Cameroon',
    0, #'countriesAndTerritories_Canada',
    0, #'countriesAndTerritories_Cape_Verde',
    0, #'countriesAndTerritories_Cases_on_an_international_conveyance_Japan',
    0, #'countriesAndTerritories_Cayman_Islands',
    0, #'countriesAndTerritories_Central_African_Republic',
    0, #'countriesAndTerritories_Chad',
    0, #'countriesAndTerritories_Chile',
    0, #'countriesAndTerritories_China',
    0, #'countriesAndTerritories_Colombia',
    0, #'countriesAndTerritories_Congo',
    0, #'countriesAndTerritories_Costa_Rica',
    0, #'countriesAndTerritories_Cote_dIvoire',
    0, #'countriesAndTerritories_Croatia',
    0, #'countriesAndTerritories_Cuba',
    0, #'countriesAndTerritories_Curacao',
    0, #'countriesAndTerritories_Cyprus',
    0, #'countriesAndTerritories_Czech_Republic',
    0, #'countriesAndTerritories_Democratic_Republic_of_the_Congo',
    0, #'countriesAndTerritories_Denmark',
    0, #'countriesAndTerritories_Djibouti',
    0, #'countriesAndTerritories_Dominica',
    0, #'countriesAndTerritories_Dominican_Republic',
    0, #'countriesAndTerritories_Ecuador',
    0, #'countriesAndTerritories_Egypt',
    0, #'countriesAndTerritories_El_Salvador',
    0, #'countriesAndTerritories_Equatorial_Guinea',
    0, #'countriesAndTerritories_Estonia',
    0, #'countriesAndTerritories_Eswatini',
    0, #'countriesAndTerritories_Ethiopia',
    0, #'countriesAndTerritories_Faroe_Islands',
    0, #'countriesAndTerritories_Fiji',
    0, #'countriesAndTerritories_Finland',
    0, #'countriesAndTerritories_France',
    0, #'countriesAndTerritories_French_Polynesia',
    0, #'countriesAndTerritories_Gabon',
    0, #'countriesAndTerritories_Gambia',
    0, #'countriesAndTerritories_Georgia',
    0, #'countriesAndTerritories_Germany',
    0, #'countriesAndTerritories_Ghana',
    0, #'countriesAndTerritories_Gibraltar',
    0, #'countriesAndTerritories_Greece',
    0, #'countriesAndTerritories_Greenland',
    0, #'countriesAndTerritories_Grenada',
    0, #'countriesAndTerritories_Guam',
    0, #'countriesAndTerritories_Guatemala',
    0, #'countriesAndTerritories_Guernsey',
    0, #'countriesAndTerritories_Guinea',
    0, #'countriesAndTerritories_Guinea_Bissau',
    0, #'countriesAndTerritories_Guyana',
    0, #'countriesAndTerritories_Haiti',
    0, #'countriesAndTerritories_Holy_See',
    0, #'countriesAndTerritories_Honduras',
    0, #'countriesAndTerritories_Hungary',
    0, #'countriesAndTerritories_Iceland',
    0, #'countriesAndTerritories_India',
    0, #'countriesAndTerritories_Indonesia',
    0, #'countriesAndTerritories_Iran',
    0, #'countriesAndTerritories_Iraq',
    0, #'countriesAndTerritories_Ireland',
    0, #'countriesAndTerritories_Isle_of_Man',
    0, #'countriesAndTerritories_Israel',
    0, #'countriesAndTerritories_Italy',
    0, #'countriesAndTerritories_Jamaica',
    0, #'countriesAndTerritories_Japan',
    0, #'countriesAndTerritories_Jersey',
    0, #'countriesAndTerritories_Jordan',
    0, #'countriesAndTerritories_Kazakhstan',
    0, #'countriesAndTerritories_Kenya',
    0, #'countriesAndTerritories_Kosovo',
    0, #'countriesAndTerritories_Kuwait',
    0, #'countriesAndTerritories_Kyrgyzstan',
    0, #'countriesAndTerritories_Laos',
    0, #'countriesAndTerritories_Latvia',
    0, #'countriesAndTerritories_Lebanon',
    0, #'countriesAndTerritories_Liberia',
    0, #'countriesAndTerritories_Libya',
    0, #'countriesAndTerritories_Liechtenstein',
    0, #'countriesAndTerritories_Lithuania',
    0, #'countriesAndTerritories_Luxembourg',
    0, #'countriesAndTerritories_Madagascar',
    0, #'countriesAndTerritories_Malaysia',
    0, #'countriesAndTerritories_Maldives',
    0, #'countriesAndTerritories_Mali',
    0, #'countriesAndTerritories_Malta',
    0, #'countriesAndTerritories_Mauritania',
    0, #'countriesAndTerritories_Mauritius',
    0, #'countriesAndTerritories_Mexico',
    0, #'countriesAndTerritories_Moldova',
    0, #'countriesAndTerritories_Monaco',
    0, #'countriesAndTerritories_Mongolia',
    0, #'countriesAndTerritories_Montenegro',
    0, #'countriesAndTerritories_Montserrat',
    0, #'countriesAndTerritories_Morocco',
    0, #'countriesAndTerritories_Mozambique',
    0, #'countriesAndTerritories_Myanmar',
    0, #'countriesAndTerritories_Namibia',
    0, #'countriesAndTerritories_Nepal',
    0, #'countriesAndTerritories_Netherlands',
    0, #'countriesAndTerritories_New_Caledonia',
    0, #'countriesAndTerritories_New_Zealand',
    0, #'countriesAndTerritories_Nicaragua',
    0, #'countriesAndTerritories_Niger',
    0, #'countriesAndTerritories_Nigeria',
    0, #'countriesAndTerritories_North_Macedonia',
    0, #'countriesAndTerritories_Norway',
    0, #'countriesAndTerritories_Oman',
    0, #'countriesAndTerritories_Pakistan',
    0, #'countriesAndTerritories_Palestine',
    0, #'countriesAndTerritories_Panama',
    0, #'countriesAndTerritories_Papua_New_Guinea',
    0, #'countriesAndTerritories_Paraguay',
    0, #'countriesAndTerritories_Peru',
    0, #'countriesAndTerritories_Philippines',
    0, #'countriesAndTerritories_Poland',
    0, #'countriesAndTerritories_Portugal',
    0, #'countriesAndTerritories_Puerto_Rico',
    0, #'countriesAndTerritories_Qatar',
    0, #'countriesAndTerritories_Romania',
    0, #'countriesAndTerritories_Russia',
    0, #'countriesAndTerritories_Rwanda',
    0, #'countriesAndTerritories_Saint_Kitts_and_Nevis',
    0, #'countriesAndTerritories_Saint_Lucia',
    0, #'countriesAndTerritories_Saint_Vincent_and_the_Grenadines',
    0, #'countriesAndTerritories_San_Marino',
    0, #'countriesAndTerritories_Saudi_Arabia',
    0, #'countriesAndTerritories_Senegal',
    0, #'countriesAndTerritories_Serbia',
    0, #'countriesAndTerritories_Seychelles',
    0, #'countriesAndTerritories_Singapore',
    0, #'countriesAndTerritories_Sint_Maarten',
    0, #'countriesAndTerritories_Slovakia',
    0, #'countriesAndTerritories_Slovenia',
    0, #'countriesAndTerritories_Somalia',
    0, #'countriesAndTerritories_South_Africa',
    0, #'countriesAndTerritories_South_Korea',
    0, #'countriesAndTerritories_Spain',
    0, #'countriesAndTerritories_Sri_Lanka',
    0, #'countriesAndTerritories_Sudan',
    0, #'countriesAndTerritories_Suriname',
    0, #'countriesAndTerritories_Sweden',
    0, #'countriesAndTerritories_Switzerland',
    0, #'countriesAndTerritories_Syria',
    0, #'countriesAndTerritories_Taiwan',
    0, #'countriesAndTerritories_Thailand',
    0, #'countriesAndTerritories_Timor_Leste',
    0, #'countriesAndTerritories_Togo',
    0, #'countriesAndTerritories_Trinidad_and_Tobago',
    0, #'countriesAndTerritories_Tunisia',
    0, #'countriesAndTerritories_Turkey',
    0, #'countriesAndTerritories_Turks_and_Caicos_islands',
    0, #'countriesAndTerritories_Uganda',
    0, #'countriesAndTerritories_Ukraine',
    0, #'countriesAndTerritories_United_Arab_Emirates',
    0, #'countriesAndTerritories_United_Kingdom',
    0, #'countriesAndTerritories_United_Republic_of_Tanzania',
    0, #'countriesAndTerritories_United_States_Virgin_Islands',
    0, #'countriesAndTerritories_United_States_of_America',
    0, #'countriesAndTerritories_Uruguay',
    0, #'countriesAndTerritories_Uzbekistan',
    0, #'countriesAndTerritories_Venezuela',
    0, #'countriesAndTerritories_Vietnam',
    0, #'countriesAndTerritories_Zambia',
    0, #'countriesAndTerritories_Zimbabwe'
]

country_and_date_to_value = [
    to_be_prediected
]

predicted = model.predict(country_and_date_to_value)

predicted_value = predicted[0]

print("there will be  {:,.2f} new cases".format(predicted_value))